services:
  noetik:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - chroma
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: python -m noetik.main --mode api --log-level INFO
    ports:
      - "${PORT:-8000}:8000"
    # Allow interactive terminal
    tty: true
    stdin_open: true

  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - chroma-data:/data
    environment:
      - IS_PERSISTENT=TRUE
      - CHROMA_SERVER_LOG_LEVEL=DEBUG

volumes:
  chroma-data:
