services:
  noetik:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - chroma
    volumes:
      - .:/app
      - cached-models:/root/.cache
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - HF_HOME=/root/.cache/huggingface
      - SENTENCE_TRANSFORMERS_HOME=/root/.cache/huggingface
    command: python -m noetik.main --mode api --log-level warning
    ports:
      - "${API_PORT:-8000}:8000"
      - "${WEBUI_PORT:-8080}:8080"
    # Allow interactive terminal
    tty: true
    stdin_open: true

  chroma:
    image: chromadb/chroma:latest
    volumes:
      - chroma-data:/data
    environment:
      - IS_PERSISTENT=TRUE
      - CHROMA_SERVER_LOG_LEVEL=WARNING

volumes:
  chroma-data:
  cached-models:
